- docker build -t udagram-frontend ./udagram-frontend
- docker tag udagram-frontend nsutanto82/udagram-frontend:v1
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push nsutanto82/udagram-frontend:v1